### ISSUE TITLE
Windows version build server error lld-link: error: duplicate symbol: public: __cdecl dmGraphics::Texture::Texture(void) in libgraphics.lib(graphics_opengl_1.o) and in libgraphics_vulkan.lib(graphics_vulkan_device_2.o)

### ISSUE THREAD

**Issue by subsoap** [defold/extension-vulkan#5] opened 2020-08-03 08:37 UTC
Tested with the extension-vulkan example project in this git and it still causes this error.

```
/vulkan/ext.manifest
	lld-link: error: duplicate symbol: public: __cdecl dmGraphics::Texture::Texture(void) in libgraphics.lib(graphics_opengl_1.o) and in libgraphics_vulkan.lib(graphics_vulkan_device_2.o)
	clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
```

Happened on 1.2.172 BETA and 1.2.171 stable

![2020-08-03 01_35_51-About](https://user-images.githubusercontent.com/409170/89162984-c133e300-d529-11ea-8730-27fa44a116ae.png)

Happened with both build servers https://build.defold.com/ and https://build-stage.defold.com/

**Comment by subsoap** [comment] 2020-08-03 08:40
Bundling a MacOS version worked fine.

Bundling a Windows version did not work.

Bundling a Linux  version did not work.

I had tested Vulkan on Windows previously and it was working then but that was almost 2 months ago at this point.

**Comment by Jhonnyg** [comment] 2020-08-03 09:02
Hm, it’s the same code so I suspect there’s something that differs in the build settings or with clang itself on those platforms. I don’t have access to Windows right now, but perhaps it’s reproducible in a linux VM.

**Comment by JCash** [comment] 2020-08-03 09:24
Not sure why/how it worked before though, but I think the error is correct, we seem to have the same name for the structs in both backends (struct Texture). Compare to how we needed to distinguish all the dmGraphics names between OpenGL/Vulkan to avoid symbol clashes.

**Comment by aglitchman** [comment] 2020-08-03 09:47
Same here - https://github.com/defold/extension-vulkan/issues/3

**Comment by subsoap** [comment] 2020-08-03 15:12
Oh yeah @aglitchman when I tested before it was with a custom manifest.

**Comment by ConnorHalford** [comment] 2021-04-05 17:45
This is still an issue on Defold 1.1.180 and extension version 1.1.0. Specifically the Vulkan extension only compiles with a custom manifest with the 'Use Vulkan' setting. The 'Use OpenGL' or 'Use Vulkan and OpenGL' settings produce the errors above

**Comment by britzl** [comment] 2021-04-10 09:17
We'll look into this soon. https://github.com/defold/defold/issues/5730

**Comment by Jhonnyg** [comment] 2021-04-16 07:47
@ConnorHalford could you test this editor https://d.defold.com/archive/dev/6e422b91dd272ae417dfcbe5988f628f889cd683/dev/editor2/Defold-x86_64-win32.zip to see if fixes your issue? or if you are on osx https://d.defold.com/archive/dev/162fbde0ded904cc8e44623515730bf3a6a70406/dev/editor2/Defold-x86_64-darwin.dmg

**Comment by ConnorHalford** [comment] 2021-04-16 17:38
@Jhonnyg that build fixes the compilation issue however it always uses Vulkan, never OpenGL (at least on Windows 10 with a graphics card that supports both (NVIDIA GeForce GTX 1050 Ti)). With the Vulkan extension present:
- No custom manifest = Vulkan, not sure whether this is correct ❔
- [Custom manifest](https://github.com/defold/extension-vulkan/files/6326977/opengl.appmanifest.txt) specifying OpenGL = Vulkan, should be OpenGL ❌
- [Custom manifest](https://github.com/defold/extension-vulkan/files/6326975/vulkan.appmanifest.txt) specifying Vulkan = Vulkan ✔️
- [Custom manifest](https://github.com/defold/extension-vulkan/files/6326976/vulkan_and_opengl.appmanifest.txt) specifying Vulkan and OpenGL = Vulkan on my device which supports both, not sure whether this actually will fall back to OpenGL on a device which doesn't support Vulkan ❔

**Comment by subsoap** [comment] 2021-04-16 19:19
Are the custom manifests even valid anymore? Maybe the Vulkan/OpenGL options should be set in the game.project file instead now.

**Comment by JCash** [comment] 2021-04-17 06:21
> specifying Vulkan and OpenGL = Vulkan on my device which supports both, not sure whether this actually will fall back to OpenGL on a device which doesn't support Vulkan 

Yes, the Vulkan backend takes precedence, as it's the newest backend and OpenGL is deprecated on some platforms.

**Comment by JCash** [comment] 2021-04-17 06:23
>No custom manifest = Vulkan, not sure whether this is correct 

This is the (implied) behavior when using the extension-vulkan.

**Comment by JCash** [comment] 2021-04-17 06:33
> specifying OpenGL = Vulkan, should be OpenGL

I think there's a misconception here.

Since the vulkan backend is actually built into the engine, the extension is just a helper to enable the correct manifest setup to choose Vulkan as the preferred backend.

The manifestation tool can be used to add/remove libraries to the build.
OpenGL is the default, so the manifestation tool doesn't _add_ any libraries to the manifest. And it won't remove the Vulkan backend, since that's not part of the default.
Remember, the manifests are merged, so the union of those library settings are used.

As such, it will be the default setup you've chosen (you've added the extension-vulkan) in your project.

* Either use the app manifest
* Or, use the extension-vulkan

**Comment by ConnorHalford** [comment] 2021-04-17 21:35
So just to clarify, if I have a custom manifest specifying both Vulkan and OpenGL, with the Vulkan extension present:

- Vulkan will be preferred on devices that support both
- Vulkan will be used on devices that don't support OpenGL
- OpenGL will be used on devices that don't support Vulkan

Is that correct? (That's the desire)

**Comment by JCash** [comment] 2021-04-18 09:04
You're adding two graphics backends: Vulkan + OpenGL.
We always test the Vulkan backend first.
If there's no support on the platform for a graphics adapter, then the next graphics adapter is tested.

**Comment by Jhonnyg** [comment] 2023-10-06 07:16
Fixed (at some point in time)

**Closed by Jhonnyg** 2023-10-06 07:16 UTC
